export enum ErrorCode {
  NO_IMAGE_CAPTURED = 'NO_IMAGE_CAPTURED',
  INVALID_PHOTO_ID = 'INVALID_PHOTO_ID',
  NO_WINES_FROM_MENU_PHOTO = 'NO_WINES_FROM_MENU_PHOTO',
  COULD_NOT_READ_BOTTLE_DETAILS = 'COULD_NOT_READ_BOTTLE_DETAILS',
  READ_MENU_FAILED = 'READ_MENU_FAILED',
  BOTTLE_SUMMARIZE_FAILED = 'BOTTLE_SUMMARIZE_FAILED',
}
